[package]
name = "asciimath"
version = "0.6.1-alpha.0"
authors = ["Gregory <gregory.mkv@gmail.com>"]
description = "Mathematical expression parser and evaluator"
license = "MIT"
documentation = "https://docs.rs/asciimath/0.3.0/asciimath/"
homepage = "https://github.com/chmln/asciimath-rs"
repository = "https://github.com/chmln/asciimath-rs.git"
readme = "README.md"

[lib]
name = "asciimath"
path = "./src/lib.rs"

[profile.release]
lto = true
opt-level = 3
debug = false

[dependencies]
lazy_static = "1.0.0"
