[package]
name = "asciimath"
version = "0.2.1-alpha.0"
authors = ["Gregory <gregory.mkv@gmail.com>"]
description = "Mathematical expression parser and evaluator"
license = "MIT"

[lib]
name = "asciimath"
path = "./src/lib.rs"

[profile.release]
lto = true
opt-level = 3
debug = false