version: 2
jobs:
  build:
    docker:
      - image: xd009642/tarpaulin

    steps:
      - checkout

      - restore_cache:
          key: project-cache

      - run:
          name: Nightly Build
          command: |
            rustup install nightly
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build

      - run:
          name: Test
          command: rustup run nightly cargo test

      - run:
          name: Coverage
          command: |
            cargo tarpaulin --out Xml
            bash <(curl -s https://codecov.io/bash)

      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

